<#
  MANUALLY-SYNCED COPY of agent/windows/collect.ps1 — do not edit this file
  independently. Re-sync (copy the main source over this file verbatim) and
  rebuild the installer (ISCC.exe) whenever the main collector changes. This
  file previously drifted out of sync and shipped without the third-party-AV
  passive-mode fix, producing false "no antivirus protection" reports on
  machines running a legitimate third-party AV — see agent/ARCHITECTURE.md's
  "Installer-source sync" note.

  ShieldAI Windows Posture Collector
  ----------------------------------
  READ-ONLY. Collects security posture from built-in Windows tooling and the
  security products already installed (Microsoft Defender, firewall, BitLocker,
  Windows Update). Makes NO changes to the system.

  It does not scan for malware itself — it reports what Defender (or another
  registered AV) has already found and its current protection state.

  Output: a single JSON document (the ShieldAI agent report schema v1) written
  to -OutFile, or to stdout if -OutFile is omitted.

  Usage:
    powershell -ExecutionPolicy Bypass -File collect.ps1 -OutFile report.json

  Exit codes: 0 always (collection failures degrade to status "unknown" so the
  scheduled run never hard-fails; partial data is more useful than none).
#>

[CmdletBinding()]
param(
  [string]$OutFile = "",
  [string]$AgentVersion = "1.2.0"
)

$ErrorActionPreference = "SilentlyContinue"

# ── helpers ───────────────────────────────────────────────────
$checks    = New-Object System.Collections.ArrayList
$events    = New-Object System.Collections.ArrayList
$nowUtc    = (Get-Date).ToUniversalTime().ToString("o")

function Add-Check {
  param(
    [string]$Id, [string]$Category, [string]$Title,
    [ValidateSet("pass","warn","fail","unknown")][string]$Status,
    [ValidateSet("info","low","medium","high","critical")][string]$Severity = "info",
    [string]$Observed = "", [string]$Detail = "", [string]$CisControl = ""
  )
  [void]$checks.Add([ordered]@{
    id = $Id; category = $Category; title = $Title; status = $Status;
    severity = $Severity; observed = $Observed; detail = $Detail; cisControl = $CisControl
  })
}

function Add-Event {
  param([string]$Source, [string]$Severity, [string]$Type, [string]$Message, $Raw = $null)
  [void]$events.Add([ordered]@{
    ts = (Get-Date).ToUniversalTime().ToString("o");
    source = $Source; severity = $Severity; type = $Type; message = $Message; raw = $Raw
  })
}

# Safely run a scriptblock; on any error, invoke the provided fallback.
function Try-Run { param([scriptblock]$Do, [scriptblock]$OnError)
  try { & $Do } catch { if ($OnError) { & $OnError } }
}

# ── host info ─────────────────────────────────────────────────
$os   = Get-CimInstance Win32_OperatingSystem
$cs   = Get-CimInstance Win32_ComputerSystem
$boot = $null
# Plain try/catch, not Try-Run — see the note further down (AV productState
# decode) for why: Try-Run's scriptblock runs in a child scope, so
# `Try-Run { $boot = ... }` would silently never update this $boot.
try { $boot = $os.LastBootUpTime.ToUniversalTime().ToString("o") } catch { }

$hostInfo = [ordered]@{
  hostname     = $env:COMPUTERNAME
  os           = "windows"
  osVersion    = "$($os.Caption) $($os.Version)"
  arch         = $env:PROCESSOR_ARCHITECTURE
  lastBootUtc  = $boot
  collectedAtUtc = $nowUtc
}

$inventory = [ordered]@{
  # installedSecurityTools must be a mutable list (not a plain @() array) —
  # several checks below call .Add() on it, which throws on a fixed-size
  # array and was silently swallowed by the enclosing Try-Run, breaking AV
  # tool reporting.
  localAdmins = @(); installedSecurityTools = (New-Object System.Collections.ArrayList);
  diskEncryption = "unknown"; pendingPatches = 0; firewall = "unknown";
  software = @()
}

# ── 1a. Full AV/security product enumeration (Security Center) ──
# Windows Security Center tracks EVERY registered AV product on the
# machine — this is how we catch a third-party AV/EDR (Bitdefender, Norton,
# Sophos, CrowdStrike, SentinelOne, etc.) instead of only ever reporting
# Defender's state, which is what an SMB is actually protected by if
# they've replaced/augmented Defender. Runs BEFORE the Defender-specific
# block below because that block needs to know whether a third-party AV is
# active to correctly interpret Defender's own state (see the note there).
#
# Plain try/catch (not the Try-Run helper) for the CIM query itself —
# Try-Run invokes its scriptblock via `&`, which runs in a child scope, so
# `Try-Run { $avProducts = ... }` would silently never update $avProducts
# in the outer scope, same footgun documented elsewhere in this file for
# $boot/$age/$nlaOn.
$avProducts = @()
try {
  $avProducts = @(Get-CimInstance -Namespace "root\SecurityCenter2" -ClassName AntiVirusProduct -ErrorAction Stop)
} catch {
  # Non-fatal: Security Center's WMI provider isn't present on Server SKUs
  # (no Action Center service) or may be restricted — the Defender-specific
  # checks below still provide baseline AV visibility in that case.
}

# Two passes: the first just decodes each product's real-time state so we
# know, BEFORE adding any check, whether a third-party AV is confirmed
# active — Defender's own Security-Center entry needs that fact to score
# itself correctly (see below), and depending on enumeration order Defender
# could come before the third-party product in $avProducts.
$decoded = @{}  # name -> { rtOn, defUpToDate }
foreach ($p in $avProducts) {
  $name = "$($p.displayName)".Trim()
  if ([string]::IsNullOrWhiteSpace($name) -or $decoded.ContainsKey($name)) { continue }
  $rtOn = $false; $defUpToDate = $false
  try {
    $stateHex = "{0:X6}" -f [int]$p.productState
    $rtOn = $stateHex.Substring(2,2) -in @("10","11")
    $defUpToDate = $stateHex.Substring(4,2) -eq "00"
  } catch { }
  $decoded[$name] = @{ rtOn = $rtOn; defUpToDate = $defUpToDate }
}
$activeThirdPartyAv = ($decoded.GetEnumerator() | Where-Object { $_.Value.rtOn -and $_.Key -ne "Windows Defender" } | Select-Object -First 1).Key

foreach ($name in $decoded.Keys) {
  if (-not ($inventory.installedSecurityTools -contains $name)) {
    [void]$inventory.installedSecurityTools.Add($name)
  }
  $rtOn = $decoded[$name].rtOn
  $defUpToDate = $decoded[$name].defUpToDate
  $statusText = "registered with Security Center"
  $checkStatus = "pass"; $checkSeverity = "info"
  if ($rtOn -and $defUpToDate) {
    $statusText = "enabled, definitions current"; $checkStatus = "pass"; $checkSeverity = "info"
  } elseif ($rtOn) {
    $statusText = "enabled, definitions may be stale"; $checkStatus = "warn"; $checkSeverity = "medium"
  } elseif ($name -eq "Windows Defender" -and $activeThirdPartyAv) {
    # Same passive-mode reasoning as av_realtime below: Defender showing
    # "disabled" here is EXPECTED when $activeThirdPartyAv is confirmed
    # active, not a gap — don't flag it as a high-severity failure.
    $statusText = "passive - $activeThirdPartyAv is the active antivirus"; $checkStatus = "pass"; $checkSeverity = "info"
  } else {
    $statusText = "protection appears disabled"; $checkStatus = "fail"; $checkSeverity = "high"
  }
  Add-Check -Id "av_product_$($name -replace '[^a-zA-Z0-9]','_')" -Category "Protect" `
    -Title "Registered AV product: $name" -Status $checkStatus -Severity $checkSeverity `
    -Observed $statusText -Detail "Reported by Windows Security Center." -CisControl "10"
}
if ($avProducts.Count -eq 0) {
  Add-Check -Id "av_registered" -Category "Protect" -Title "Registered AV products" `
    -Status "warn" -Severity "medium" -Observed "None registered with Security Center" `
    -Detail "No antivirus product is registered with Windows Security Center." -CisControl "10"
}

# ── 1b. Microsoft Defender's own detailed state ─────────────────
Try-Run {
  $mp = Get-MpComputerStatus
  if ($mp) {
    # Real-time protection. When a third-party AV (e.g. Bitdefender) is
    # installed, Windows correctly and intentionally puts Defender into
    # Passive Mode — RealTimeProtectionEnabled goes to $false as EXPECTED
    # behavior, not a protection gap. The old version of this check treated
    # that as an unconditional high-severity failure, which produced a
    # false "no real-time protection" finding on every machine running a
    # third-party AV — exactly the kind of false negative that made a
    # correctly-installed Bitdefender look like it wasn't being detected.
    # AMRunningMode (values: Normal | Passive Mode | SxS Passive Mode |
    # EDR Block Mode) is what tells us WHY it's off, so we can tell a real
    # gap apart from expected passive-mode behavior.
    $passiveMode = ($mp.PSObject.Properties.Name -contains "AMRunningMode") -and ($mp.AMRunningMode -ne "Normal")
    if ($mp.RealTimeProtectionEnabled) {
      Add-Check -Id "av_realtime" -Category "Protect" -Title "Antivirus real-time protection" `
        -Status "pass" -Severity "info" -Observed "Enabled (Microsoft Defender)" `
        -Detail "Microsoft Defender real-time protection is enabled." -CisControl "10"
    } elseif ($passiveMode -and $activeThirdPartyAv) {
      Add-Check -Id "av_realtime" -Category "Protect" -Title "Antivirus real-time protection" `
        -Status "pass" -Severity "info" -Observed "Enabled ($activeThirdPartyAv)" `
        -Detail "Defender is intentionally in $($mp.AMRunningMode) because $activeThirdPartyAv is the active antivirus — this is expected, not a gap. See the 'Registered AV product: $activeThirdPartyAv' check for its own status." -CisControl "10"
    } elseif ($passiveMode) {
      Add-Check -Id "av_realtime" -Category "Protect" -Title "Antivirus real-time protection" `
        -Status "warn" -Severity "medium" -Observed "Defender passive ($($mp.AMRunningMode)), no active third-party AV confirmed" `
        -Detail "Defender reports $($mp.AMRunningMode) but no other registered antivirus product could be confirmed active via Security Center — verify a real-time AV is actually running." -CisControl "10"
    } else {
      Add-Check -Id "av_realtime" -Category "Protect" -Title "Antivirus real-time protection" `
        -Status "fail" -Severity "high" -Observed "Disabled" `
        -Detail "Real-time protection is OFF and no other antivirus is active. The endpoint is not actively protected." -CisControl "10"
    }
    # Signature freshness
    $age = $null
    # Plain try/catch, not Try-Run — see the note further down (AV productState
    # decode) for why: Try-Run's scriptblock runs in a child scope, so this
    # assignment to $age would silently never reach the check below,
    # permanently disabling the signature-freshness check.
    try { $age = (New-TimeSpan -Start $mp.AntivirusSignatureLastUpdated -End (Get-Date)).Days } catch { }
    if ($age -ne $null) {
      if ($age -le 3) {
        Add-Check -Id "av_signatures" -Category "Protect" -Title "Antivirus signature freshness" `
          -Status "pass" -Severity "info" -Observed "$age day(s) old" `
          -Detail "Defender definitions are current." -CisControl "10"
      } elseif ($age -le 14) {
        Add-Check -Id "av_signatures" -Category "Protect" -Title "Antivirus signature freshness" `
          -Status "warn" -Severity "medium" -Observed "$age days old" `
          -Detail "Defender definitions are getting stale." -CisControl "10"
      } else {
        Add-Check -Id "av_signatures" -Category "Protect" -Title "Antivirus signature freshness" `
          -Status "fail" -Severity "high" -Observed "$age days old" `
          -Detail "Defender definitions are badly out of date." -CisControl "10"
      }
    }
    # Tamper protection
    if ($mp.PSObject.Properties.Name -contains "IsTamperProtected") {
      Add-Check -Id "av_tamper" -Category "Protect" -Title "Tamper protection" `
        -Status ($(if ($mp.IsTamperProtected) {"pass"} else {"warn"})) `
        -Severity ($(if ($mp.IsTamperProtected) {"info"} else {"medium"})) `
        -Observed ($(if ($mp.IsTamperProtected) {"Enabled"} else {"Disabled"})) `
        -Detail "Tamper protection prevents attackers disabling Defender." -CisControl "10"
    }
    [void]$inventory.installedSecurityTools.Add("Microsoft Defender")
  }
} {
  Add-Check -Id "av_realtime" -Category "Protect" -Title "Antivirus real-time protection" `
    -Status "unknown" -Severity "medium" -Observed "Not determinable" `
    -Detail "Could not query Defender directly. See the 'Registered AV product' checks above for what Security Center reports instead." -CisControl "10"
}

# Active/quarantined threats → events
Try-Run {
  $threats = Get-MpThreatDetection | Sort-Object InitialDetectionTime -Descending | Select-Object -First 25
  foreach ($t in $threats) {
    $name = $t.ThreatName; if (-not $name) { $name = "Unknown threat" }
    Add-Event -Source "defender" -Severity "high" -Type "malware_detected" `
      -Message "Defender detection: $name" -Raw ([ordered]@{
        threatId = $t.ThreatID; detectedAt = "$($t.InitialDetectionTime)";
        action = "$($t.CleaningActionID)"; resources = @($t.Resources)
      })
  }
  if ($threats -and $threats.Count -gt 0) {
    Add-Check -Id "av_threats" -Category "Detect" -Title "Recent malware detections" `
      -Status "warn" -Severity "high" -Observed "$($threats.Count) detection(s)" `
      -Detail "Defender has recorded recent threat detections; review the events list." -CisControl "10"
  } else {
    Add-Check -Id "av_threats" -Category "Detect" -Title "Recent malware detections" `
      -Status "pass" -Severity "info" -Observed "None recorded" `
      -Detail "No recent Defender threat detections." -CisControl "10"
  }
}

# ── 1c. Third-party EDR/AV fallback (service/process presence) ──
# Some centrally-managed EDR products (CrowdStrike Falcon is the most common
# case) don't register with Windows Security Center at all in enterprise
# deployments, so section 1a's enumeration alone can miss them — an active
# EDR would still show up as "no AV detected." This checks for the vendor's
# own service/process directly, as a second, independent signal. Bitdefender
# is included here too as a backup path to section 1a, not a replacement for
# it — if Security Center enumeration ever misses it (e.g. certain
# GravityZone configurations), this still catches it.
#
# NOTE: these are the best publicly-documented service/process names for
# each vendor, but — like the equivalent Linux/macOS checks — they haven't
# all been verified against a live install of every product. Spot-check
# against a real endpoint before fully trusting a specific vendor's entry.
$edrVendors = @(
  @{ Name = "CrowdStrike Falcon"; Services = @("CSFalconService") },
  @{ Name = "SentinelOne"; Services = @("SentinelAgent","SentinelServiceHost") },
  @{ Name = "Sophos"; Services = @("Sophos MCS Client"); Processes = @("SophosHealth") },
  @{ Name = "ESET"; Services = @("ekrn"); Processes = @("ekrn") },
  @{ Name = "Malwarebytes"; Services = @("MBAMService") },
  @{ Name = "Wazuh"; Services = @("WazuhSvc") },
  @{ Name = "Bitdefender"; Services = @("VSSERV"); Processes = @("bdservicehost","EPSecurityService") }
)
$edrFound = New-Object System.Collections.ArrayList
foreach ($vendor in $edrVendors) {
  $hit = $false
  foreach ($svc in @($vendor.Services)) {
    if ($svc -and (Get-Service -Name $svc -ErrorAction SilentlyContinue)) { $hit = $true; break }
  }
  if (-not $hit) {
    foreach ($proc in @($vendor.Processes)) {
      if ($proc -and (Get-Process -Name $proc -ErrorAction SilentlyContinue)) { $hit = $true; break }
    }
  }
  if ($hit) {
    [void]$edrFound.Add($vendor.Name)
    if (-not ($inventory.installedSecurityTools -contains $vendor.Name)) {
      [void]$inventory.installedSecurityTools.Add($vendor.Name)
    }
  }
}
if ($edrFound.Count -gt 0) {
  $alreadyRegisteredNames = @($decoded.Keys)
  $newlyFoundOnly = @($edrFound | Where-Object { $alreadyRegisteredNames -notcontains $_ })
  $detailSuffix = if ($newlyFoundOnly.Count -gt 0) { " Found via service/process detection, not registered with Windows Security Center: $($newlyFoundOnly -join ', ')." } else { "" }
  Add-Check -Id "edr_fallback" -Category "Protect" -Title "Third-party EDR/AV (service detection)" `
    -Status "pass" -Severity "info" -Observed "$($edrFound -join ', ')" `
    -Detail "Detected via vendor service/process presence.$detailSuffix" -CisControl "10"
}
# If nothing is found here, no check is emitted — section 1a's
# "av_registered"/av_realtime checks above already cover the "nothing
# detected at all" case, and a third redundant warning would just be noise.

# ── 2. Firewall ───────────────────────────────────────────────
Try-Run {
  $profiles = Get-NetFirewallProfile
  $allOn = ($profiles | Where-Object { -not $_.Enabled } | Measure-Object).Count -eq 0
  $inventory.firewall = if ($allOn) { "all profiles enabled" } else { "one or more profiles disabled" }
  Add-Check -Id "firewall" -Category "Protect" -Title "Host firewall" `
    -Status ($(if ($allOn) {"pass"} else {"fail"})) `
    -Severity ($(if ($allOn) {"info"} else {"high"})) `
    -Observed $inventory.firewall `
    -Detail "Windows Firewall should be enabled on Domain, Private, and Public profiles." -CisControl "4"
} {
  Add-Check -Id "firewall" -Category "Protect" -Title "Host firewall" -Status "unknown" `
    -Severity "medium" -Observed "Not determinable" -Detail "Could not query firewall profiles." -CisControl "4"
}

# ── 3. Disk encryption (BitLocker) ────────────────────────────
Try-Run {
  $sys = $env:SystemDrive
  $vol = Get-BitLockerVolume -MountPoint $sys
  $on  = $vol.ProtectionStatus -eq "On"
  $inventory.diskEncryption = if ($on) { "BitLocker On ($sys)" } else { "BitLocker Off ($sys)" }
  Add-Check -Id "disk_encryption" -Category "Protect" -Title "Disk encryption" `
    -Status ($(if ($on) {"pass"} else {"fail"})) `
    -Severity ($(if ($on) {"info"} else {"high"})) `
    -Observed $inventory.diskEncryption `
    -Detail "The system drive should be encrypted to protect data at rest." -CisControl "3"
} {
  Add-Check -Id "disk_encryption" -Category "Protect" -Title "Disk encryption" -Status "unknown" `
    -Severity "medium" -Observed "Not determinable" `
    -Detail "Could not query BitLocker (may require elevation, or no TPM)." -CisControl "3"
}

# ── 4. Pending OS updates ─────────────────────────────────────
Try-Run {
  $session  = New-Object -ComObject Microsoft.Update.Session
  $searcher = $session.CreateUpdateSearcher()
  $result   = $searcher.Search("IsInstalled=0 and IsHidden=0")
  $count    = $result.Updates.Count
  $inventory.pendingPatches = [int]$count
  if ($count -eq 0) {
    Add-Check -Id "patches" -Category "Identify" -Title "Pending OS updates" `
      -Status "pass" -Severity "info" -Observed "0 pending" -Detail "No pending Windows updates." -CisControl "7"
  } elseif ($count -le 5) {
    Add-Check -Id "patches" -Category "Identify" -Title "Pending OS updates" `
      -Status "warn" -Severity "medium" -Observed "$count pending" -Detail "Some Windows updates are pending." -CisControl "7"
  } else {
    Add-Check -Id "patches" -Category "Identify" -Title "Pending OS updates" `
      -Status "fail" -Severity "high" -Observed "$count pending" -Detail "Many Windows updates are pending; patch promptly." -CisControl "7"
  }
} {
  Add-Check -Id "patches" -Category "Identify" -Title "Pending OS updates" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not query Windows Update." -CisControl "7"
}

# ── 5. Local administrators ───────────────────────────────────
Try-Run {
  $admins = Get-LocalGroupMember -Group "Administrators" | ForEach-Object { $_.Name }
  $inventory.localAdmins = @($admins)
  $n = @($admins).Count
  Add-Check -Id "local_admins" -Category "Identify" -Title "Local administrator accounts" `
    -Status ($(if ($n -le 3) {"pass"} elseif ($n -le 6) {"warn"} else {"fail"})) `
    -Severity ($(if ($n -le 3) {"info"} elseif ($n -le 6) {"medium"} else {"high"})) `
    -Observed "$n admin account(s)" `
    -Detail "Limit local admin rights to the minimum necessary (least privilege)." -CisControl "5"
} {
  Add-Check -Id "local_admins" -Category "Identify" -Title "Local administrator accounts" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not enumerate local Administrators group." -CisControl "5"
}

# ── 6. Screen lock / inactivity timeout ───────────────────────
Try-Run {
  $val = (Get-ItemProperty "HKCU:\Control Panel\Desktop" -Name ScreenSaveActive).ScreenSaveActive
  $sec = (Get-ItemProperty "HKCU:\Control Panel\Desktop" -Name ScreenSaveTimeOut).ScreenSaveTimeOut
  $secure = (Get-ItemProperty "HKCU:\Control Panel\Desktop" -Name ScreenSaverIsSecure).ScreenSaverIsSecure
  $ok = ($val -eq 1 -and [int]$sec -le 900 -and $secure -eq 1)
  Add-Check -Id "screen_lock" -Category "Protect" -Title "Automatic screen lock" `
    -Status ($(if ($ok) {"pass"} else {"warn"})) `
    -Severity ($(if ($ok) {"info"} else {"low"})) `
    -Observed ($(if ($ok) {"Secured, <=15 min"} else {"Not enforced / too long"})) `
    -Detail "Screens should auto-lock after a short idle period and require a password." -CisControl "4"
}

# ── 7. Guest account ────────────────────────────────────────────
Try-Run {
  $guest = Get-LocalUser -Name "Guest" -ErrorAction Stop
  Add-Check -Id "guest_account" -Category "Protect" -Title "Guest account disabled" `
    -Status ($(if (-not $guest.Enabled) {"pass"} else {"fail"})) `
    -Severity ($(if (-not $guest.Enabled) {"info"} else {"high"})) `
    -Observed ($(if ($guest.Enabled) {"Enabled"} else {"Disabled"})) `
    -Detail "The built-in Guest account should stay disabled - it's a common low-friction entry point." -CisControl "5"
} {
  Add-Check -Id "guest_account" -Category "Protect" -Title "Guest account disabled" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not query the local Guest account." -CisControl "5"
}

# ── 8. Legacy SMBv1 protocol ────────────────────────────────────
Try-Run {
  $smb1 = Get-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -ErrorAction Stop
  $on = $smb1.State -eq "Enabled"
  Add-Check -Id "smb1" -Category "Protect" -Title "Legacy SMBv1 protocol" `
    -Status ($(if (-not $on) {"pass"} else {"fail"})) `
    -Severity ($(if (-not $on) {"info"} else {"critical"})) `
    -Observed ($(if ($on) {"Enabled"} else {"Disabled"})) `
    -Detail "SMBv1 is a legacy, vulnerable protocol (e.g. EternalBlue/WannaCry) and should stay disabled unless a specific legacy device requires it." -CisControl "4"
} {
  Add-Check -Id "smb1" -Category "Protect" -Title "Legacy SMBv1 protocol" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not query the SMB1Protocol optional feature." -CisControl "4"
}

# ── 9. Remote Desktop (RDP) exposure ────────────────────────────
Try-Run {
  $rdpDeny = (Get-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -ErrorAction Stop).fDenyTSConnections
  if ($rdpDeny -eq 0) {
    $nlaOn = $false
    # Plain try/catch, not Try-Run — see the note above the AV productState
    # decode for why: Try-Run's scriptblock invocation would shadow $nlaOn
    # instead of updating it.
    try {
      $nlaOn = ((Get-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -ErrorAction Stop).UserAuthentication -eq 1)
    } catch { }
    Add-Check -Id "rdp_exposure" -Category "Protect" -Title "Remote Desktop (RDP)" `
      -Status ($(if ($nlaOn) {"warn"} else {"fail"})) `
      -Severity ($(if ($nlaOn) {"medium"} else {"critical"})) `
      -Observed ($(if ($nlaOn) {"Enabled, NLA required"} else {"Enabled, NLA NOT required"})) `
      -Detail "RDP is a common ransomware entry point. If it must stay enabled, Network Level Authentication should be required and access restricted (VPN/firewall)." -CisControl "4"
  } else {
    Add-Check -Id "rdp_exposure" -Category "Protect" -Title "Remote Desktop (RDP)" `
      -Status "pass" -Severity "info" -Observed "Disabled" -Detail "Remote Desktop is disabled." -CisControl "4"
  }
} {
  Add-Check -Id "rdp_exposure" -Category "Protect" -Title "Remote Desktop (RDP)" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not query Remote Desktop configuration." -CisControl "4"
}

# ── 10. Installed software inventory (read-only) ───────────────
# Enumerates installed applications with versions from the registry uninstall
# keys — the standard, fast, read-only method (avoids the slow Win32_Product
# WMI query, which can trigger MSI reconfiguration). Covers 64-bit, 32-bit, and
# per-user installs. This feeds ShieldAI's CVE matching (name + version -> NVD).
Try-Run {
  $paths = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*",
    "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*"
  )
  $seen = @{}
  $sw = New-Object System.Collections.ArrayList
  foreach ($p in $paths) {
    Get-ItemProperty $p -ErrorAction SilentlyContinue | ForEach-Object {
      $name = $_.DisplayName
      $ver  = $_.DisplayVersion
      # Skip entries with no name, system components, and updates/hotfixes.
      if ([string]::IsNullOrWhiteSpace($name)) { return }
      if ($_.SystemComponent -eq 1) { return }
      if ($name -match "^(KB\d+|Security Update|Update for|Hotfix)") { return }
      $key = "$name|$ver"
      if ($seen.ContainsKey($key)) { return }
      $seen[$key] = $true
      [void]$sw.Add([ordered]@{
        name    = "$name".Trim()
        version = if ([string]::IsNullOrWhiteSpace($ver)) { "" } else { "$ver".Trim() }
      })
    }
  }
  # Cap the list to keep report payloads reasonable; most relevant for CVEs are
  # the named third-party apps, which this comfortably covers.
  $inventory.software = @($sw | Sort-Object { $_.name } | Select-Object -First 200)
} {
  # Non-fatal: if the scan fails, software stays an empty array (honest — no
  # fabricated inventory), and CVE matching falls back to OS + assessment data.
  $inventory.software = @()
}

# ── 11. VPN client installed ───────────────────────────────────
$vpnVendors = @(
  @{ Name = "OpenVPN"; Services = @("OpenVPNService"); Processes = @("openvpn","openvpn-gui") },
  @{ Name = "Cisco AnyConnect"; Services = @("vpnagent"); Processes = @("vpnui") },
  @{ Name = "WireGuard"; Services = @("WireGuardTunnel*"); Processes = @("wireguard") },
  @{ Name = "NordVPN"; Services = @("nordvpn-service"); Processes = @("NordVPN") },
  @{ Name = "Tailscale"; Services = @("Tailscale"); Processes = @("tailscaled") }
)
$vpnClientsFound = New-Object System.Collections.ArrayList
foreach ($vendor in $vpnVendors) {
  $hit = $false
  foreach ($svc in @($vendor.Services)) {
    if ($svc -and (Get-Service -Name $svc -ErrorAction SilentlyContinue)) { $hit = $true; break }
  }
  if (-not $hit) {
    foreach ($proc in @($vendor.Processes)) {
      if ($proc -and (Get-Process -Name $proc -ErrorAction SilentlyContinue)) { $hit = $true; break }
    }
  }
  if ($hit) { [void]$vpnClientsFound.Add($vendor.Name) }
}
$inventory.vpn = [ordered]@{ installedClients = @($vpnClientsFound); tunnelActive = $false; activeTunnelClient = "" }
if ($vpnClientsFound.Count -gt 0) {
  Add-Check -Id "vpn_client_installed" -Category "Protect" -Title "VPN client installed" `
    -Status "pass" -Severity "info" -Observed "$($vpnClientsFound -join ', ')" `
    -Detail "A VPN client is installed on this endpoint." -CisControl "12"
} else {
  Add-Check -Id "vpn_client_installed" -Category "Protect" -Title "VPN client installed" `
    -Status "warn" -Severity "low" -Observed "None detected" `
    -Detail "No known VPN client software was found on this endpoint." -CisControl "12"
}

# ── 12. VPN tunnel actively connected ──────────────────────────
# Distinct from "installed" above — a client can be present but not
# currently protecting the session. Matches on BOTH InterfaceDescription
# and Name because several vendors share the Wintun driver (WireGuard,
# newer OpenVPN, Tailscale, NordVPN's NordLynx all present as "Wintun
# Userspace Tunnel"), so Name (vendor/tunnel-specific) is needed to
# disambiguate; falls back to attributing an ambiguous Wintun adapter to
# whichever VPN client's service/process was already confirmed running.
Try-Run {
  $upAdapters = @(Get-NetAdapter -ErrorAction Stop | Where-Object { $_.Status -eq "Up" })
  $tunnelPatterns = @(
    @{ Pattern = "Tailscale"; Vendor = "Tailscale" },
    @{ Pattern = "NordLynx"; Vendor = "NordVPN" },
    @{ Pattern = "WireGuard"; Vendor = "WireGuard" },
    @{ Pattern = "TAP-Windows Adapter"; Vendor = "OpenVPN" },
    @{ Pattern = "Cisco AnyConnect"; Vendor = "Cisco AnyConnect" },
    @{ Pattern = "Wintun"; Vendor = $null }
  )
  $activeVendor = $null
  foreach ($a in $upAdapters) {
    $desc = "$($a.InterfaceDescription)"; $nm = "$($a.Name)"
    foreach ($tp in $tunnelPatterns) {
      if ($desc -notmatch [regex]::Escape($tp.Pattern) -and $nm -notmatch [regex]::Escape($tp.Pattern)) { continue }
      if ($tp.Vendor) { $activeVendor = $tp.Vendor }
      else {
        foreach ($v in $vpnClientsFound) {
          if ($nm -match [regex]::Escape($v)) { $activeVendor = $v; break }
        }
        if (-not $activeVendor -and $vpnClientsFound.Count -gt 0) { $activeVendor = $vpnClientsFound[0] }
      }
      if ($activeVendor) { break }
    }
    if ($activeVendor) { break }
  }
  if ($activeVendor) {
    $inventory.vpn.tunnelActive = $true
    $inventory.vpn.activeTunnelClient = $activeVendor
    Add-Check -Id "vpn_tunnel_active" -Category "Protect" -Title "VPN tunnel active" `
      -Status "pass" -Severity "info" -Observed "Connected ($activeVendor)" `
      -Detail "An active VPN tunnel was detected via network adapter state." -CisControl "12"
  } elseif ($vpnClientsFound.Count -gt 0) {
    Add-Check -Id "vpn_tunnel_active" -Category "Protect" -Title "VPN tunnel active" `
      -Status "warn" -Severity "low" -Observed "Installed but not connected" `
      -Detail "A VPN client is installed but no active tunnel was detected right now." -CisControl "12"
  } else {
    Add-Check -Id "vpn_tunnel_active" -Category "Protect" -Title "VPN tunnel active" `
      -Status "warn" -Severity "low" -Observed "No VPN client installed" `
      -Detail "No VPN client is installed, so no tunnel can be active." -CisControl "12"
  }
} {
  Add-Check -Id "vpn_tunnel_active" -Category "Protect" -Title "VPN tunnel active" -Status "unknown" `
    -Severity "low" -Observed "Not determinable" -Detail "Could not enumerate network adapters." -CisControl "12"
}

# ── 13. Password managers ──────────────────────────────────────
# Third-party desktop apps: name-match against the software inventory
# already built in section 10, rather than re-scanning the registry again.
$pwdMgrNames = @("1Password","LastPass","Bitwarden","Dashlane","KeePass")
$pwdMgrsFound = New-Object System.Collections.ArrayList
foreach ($sw in $inventory.software) {
  foreach ($pm in $pwdMgrNames) {
    if ($sw.name -match [regex]::Escape($pm) -and -not ($pwdMgrsFound -contains $pm)) {
      [void]$pwdMgrsFound.Add($pm)
    }
  }
}
$inventory.passwordManagers = [ordered]@{
  thirdPartyInstalled = @($pwdMgrsFound)
  browserNative = [ordered]@{ chrome = "not-installed"; edge = "not-installed"; firefox = "not-installed" }
}
if ($pwdMgrsFound.Count -gt 0) {
  Add-Check -Id "password_manager_installed" -Category "Protect" -Title "Password manager installed" `
    -Status "pass" -Severity "info" -Observed "$($pwdMgrsFound -join ', ')" `
    -Detail "A third-party password manager is installed on this endpoint." -CisControl "6"
} else {
  Add-Check -Id "password_manager_installed" -Category "Protect" -Title "Password manager installed" `
    -Status "warn" -Severity "low" -Observed "None detected" `
    -Detail "No known third-party password manager was found on this endpoint." -CisControl "6"
}

# ── 14. Browser-native password manager, Safe Browsing/SmartScreen, version ──
# Reads each browser's own JSON Preferences file — same idiom as
# agent-run.ps1's Read-Json (Get-Content -Raw | ConvertFrom-Json, guarded by
# Test-Path) — checking the enterprise Group-Policy override first since
# it's authoritative when set. This is genuinely new collector logic; no
# prior Preferences-file or Policy-key read exists elsewhere in this script.
function Read-JsonFile($path) {
  if (Test-Path $path) {
    try { return (Get-Content $path -Raw -ErrorAction Stop | ConvertFrom-Json) } catch { return $null }
  }
  return $null
}
function Get-ChromiumProfilePrefs($userDataDir) {
  $results = New-Object System.Collections.ArrayList
  if (Test-Path $userDataDir) {
    Get-ChildItem $userDataDir -Directory -ErrorAction SilentlyContinue |
      Where-Object { $_.Name -eq "Default" -or $_.Name -match "^Profile \d+$" } |
      ForEach-Object {
        $prefs = Read-JsonFile (Join-Path $_.FullName "Preferences")
        if ($prefs) { [void]$results.Add($prefs) }
      }
  }
  return $results
}

# Major-version floor per browser, "current stable major minus ~2" as of
# when this was written. Must be refreshed periodically and kept numerically
# identical across the Windows/Linux/macOS collectors — see
# agent/ARCHITECTURE.md's installer-sync / version-baseline note.
$MinSupportedBrowserMajor = @{ chrome = 128; edge = 128; firefox = 128 }

$inventory.browsers = New-Object System.Collections.ArrayList
$chromiumBrowsers = @(
  @{ Key = "chrome"; Name = "Google Chrome"; Exe = "$env:ProgramFiles\Google\Chrome\Application\chrome.exe";
     PrefsDir = "$env:LOCALAPPDATA\Google\Chrome\User Data"; PolicyKey = "HKLM:\SOFTWARE\Policies\Google\Chrome" },
  @{ Key = "edge"; Name = "Microsoft Edge"; Exe = "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe";
     PrefsDir = "$env:LOCALAPPDATA\Microsoft\Edge\User Data"; PolicyKey = "HKLM:\SOFTWARE\Policies\Microsoft\Edge" }
)
foreach ($b in $chromiumBrowsers) {
  if (-not (Test-Path $b.Exe)) { continue }
  $version = "unknown"
  try { $version = (Get-Item $b.Exe -ErrorAction Stop).VersionInfo.ProductVersion } catch { }
  $major = 0
  try { $major = [int](("$version" -split "\.")[0]) } catch { }
  $current = ($major -ge $MinSupportedBrowserMajor[$b.Key])

  # @()-wrap: PowerShell unwraps a single-element collection to a bare
  # scalar on return, which would silently drop .Count here whenever a
  # browser has exactly one profile (confirmed against a real Edge install
  # with only "Default" — the same class of gotcha $avProducts/$sw guard
  # against elsewhere in this file with the same @() idiom).
  $profiles = @(Get-ChromiumProfilePrefs $b.PrefsDir)
  $pwdMgrEnabled = "unknown"; $safeBrowsing = "unknown"

  # Policy overrides win when set, regardless of the per-profile Preferences
  # value. Edge's SmartScreen is checked as its own key (SmartScreenEnabled)
  # alongside Chrome's SafeBrowsingProtectionLevel — Edge (Chromium-based)
  # also honors the standard SafeBrowsingProtectionLevel policy, so either
  # name is checked generically here rather than branching per browser.
  $policyPwdMgr = $null; $policySafeBrowsing = $null
  try {
    $pol = Get-ItemProperty $b.PolicyKey -ErrorAction Stop
    if ($pol.PSObject.Properties.Name -contains "PasswordManagerEnabled") { $policyPwdMgr = $pol.PasswordManagerEnabled }
    if ($pol.PSObject.Properties.Name -contains "SafeBrowsingProtectionLevel") { $policySafeBrowsing = [int]$pol.SafeBrowsingProtectionLevel -ge 1 }
    elseif ($pol.PSObject.Properties.Name -contains "SmartScreenEnabled") { $policySafeBrowsing = [int]$pol.SmartScreenEnabled -eq 1 }
  } catch { }

  if ($policyPwdMgr -ne $null) {
    $pwdMgrEnabled = if ($policyPwdMgr -eq 1) { "enabled" } else { "disabled" }
  } elseif ($profiles.Count -gt 0) {
    # credentials_enable_service defaults to true (enabled) when unset, so
    # only an explicit false counts as "disabled" — matches Chromium's
    # actual default-on behavior rather than treating "not customized" as off.
    $anyDisabled = @($profiles | Where-Object { $_.credentials_enable_service -eq $false })
    $pwdMgrEnabled = if ($anyDisabled.Count -gt 0) { "disabled" } else { "enabled" }
  }

  if ($policySafeBrowsing -ne $null) {
    $safeBrowsing = if ($policySafeBrowsing) { "enabled" } else { "disabled" }
  } elseif ($profiles.Count -gt 0) {
    # For the unmanaged/no-policy default state, this reads the standard
    # Chromium `safebrowsing.enabled` preference (default-on, same
    # explicit-false-only-counts-as-disabled reasoning as above). Edge's
    # own SmartScreen has additional settings beyond Safe Browsing in some
    # builds — if a future check needs finer-grained SmartScreen state
    # specifically (not just the shared Safe-Browsing subsystem), verify
    # the exact unmanaged-default Preferences key against a real Edge
    # profile before relying on it; not guessed here.
    $anyDisabled = @($profiles | Where-Object { $_.safebrowsing -and $_.safebrowsing.enabled -eq $false })
    $safeBrowsing = if ($anyDisabled.Count -gt 0) { "disabled" } else { "enabled" }
  }

  [void]$inventory.browsers.Add([ordered]@{
    name = $b.Name; version = $version; safeBrowsing = $safeBrowsing; currentVersion = $current
  })
  $inventory.passwordManagers.browserNative.$($b.Key) = $pwdMgrEnabled

  if ($pwdMgrEnabled -ne "unknown") {
    Add-Check -Id "browser_pwdmgr_$($b.Key)" -Category "Protect" -Title "$($b.Name) password manager" `
      -Status ($(if ($pwdMgrEnabled -eq "enabled") {"pass"} else {"warn"})) `
      -Severity ($(if ($pwdMgrEnabled -eq "enabled") {"info"} else {"low"})) `
      -Observed $pwdMgrEnabled -Detail "Built-in $($b.Name) password manager state." -CisControl "6"
  }
  if ($safeBrowsing -ne "unknown") {
    Add-Check -Id "browser_safebrowsing_$($b.Key)" -Category "Protect" -Title "$($b.Name) Safe Browsing / SmartScreen" `
      -Status ($(if ($safeBrowsing -eq "enabled") {"pass"} else {"fail"})) `
      -Severity ($(if ($safeBrowsing -eq "enabled") {"info"} else {"medium"})) `
      -Observed $safeBrowsing -Detail "Built-in phishing/malware protection state." -CisControl "9"
  }
  Add-Check -Id "browser_version_$($b.Key)" -Category "Identify" -Title "$($b.Name) version currency" `
    -Status ($(if ($current) {"pass"} else {"warn"})) `
    -Severity ($(if ($current) {"info"} else {"medium"})) `
    -Observed "$version" -Detail "Installed browser version compared against the supported baseline." -CisControl "7"
}

# Firefox uses a different preferences format entirely (prefs.js, a
# JS-literal text file, not JSON) — handled separately rather than folded
# into the Chromium loop above, which is a genuinely different idiom, not
# an oversight.
$firefoxExe = "$env:ProgramFiles\Mozilla Firefox\firefox.exe"
if (Test-Path $firefoxExe) {
  $version = "unknown"
  try { $version = (Get-Item $firefoxExe -ErrorAction Stop).VersionInfo.ProductVersion } catch { }
  $major = 0
  try { $major = [int](("$version" -split "\.")[0]) } catch { }
  $current = ($major -ge $MinSupportedBrowserMajor["firefox"])

  $pwdMgrEnabled = "unknown"; $safeBrowsing = "unknown"
  $profileLines = @()
  try {
    $profileFiles = Get-ChildItem "$env:APPDATA\Mozilla\Firefox\Profiles\*.default*\prefs.js" -ErrorAction SilentlyContinue
    foreach ($pf in $profileFiles) { $profileLines += @(Get-Content $pf.FullName -ErrorAction SilentlyContinue) }
  } catch { }
  if ($profileLines.Count -gt 0) {
    $remember = @($profileLines | Where-Object { $_ -match 'user_pref\("signon\.rememberSignons",\s*(true|false)\)' })
    # Absence of the pref means the Firefox default (enabled) hasn't been
    # overridden — same default-on reasoning as the Chromium checks above.
    $pwdMgrEnabled = if ($remember.Count -gt 0 -and $remember[0] -match "false") { "disabled" } else { "enabled" }
    $malwareOff = @($profileLines | Where-Object { $_ -match 'user_pref\("browser\.safebrowsing\.malware\.enabled",\s*false\)' })
    $phishingOff = @($profileLines | Where-Object { $_ -match 'user_pref\("browser\.safebrowsing\.phishing\.enabled",\s*false\)' })
    $safeBrowsing = if ($malwareOff.Count -gt 0 -or $phishingOff.Count -gt 0) { "disabled" } else { "enabled" }
  }

  [void]$inventory.browsers.Add([ordered]@{
    name = "Mozilla Firefox"; version = $version; safeBrowsing = $safeBrowsing; currentVersion = $current
  })
  $inventory.passwordManagers.browserNative.firefox = $pwdMgrEnabled

  Add-Check -Id "browser_pwdmgr_firefox" -Category "Protect" -Title "Firefox password manager" `
    -Status ($(if ($pwdMgrEnabled -eq "enabled") {"pass"} else {"warn"})) `
    -Severity ($(if ($pwdMgrEnabled -eq "enabled") {"info"} else {"low"})) `
    -Observed $pwdMgrEnabled -Detail "Built-in Firefox password manager state." -CisControl "6"
  Add-Check -Id "browser_safebrowsing_firefox" -Category "Protect" -Title "Firefox Safe Browsing" `
    -Status ($(if ($safeBrowsing -eq "enabled") {"pass"} else {"fail"})) `
    -Severity ($(if ($safeBrowsing -eq "enabled") {"info"} else {"medium"})) `
    -Observed $safeBrowsing -Detail "Built-in phishing/malware protection state." -CisControl "9"
  Add-Check -Id "browser_version_firefox" -Category "Identify" -Title "Firefox version currency" `
    -Status ($(if ($current) {"pass"} else {"warn"})) `
    -Severity ($(if ($current) {"info"} else {"medium"})) `
    -Observed "$version" -Detail "Installed browser version compared against the supported baseline." -CisControl "7"
}

# ── assemble report ───────────────────────────────────────────
$report = [ordered]@{
  agentVersion = $AgentVersion
  schema       = 1
  host         = $hostInfo
  checks       = $checks
  events       = $events
  inventory    = $inventory
}

$json = $report | ConvertTo-Json -Depth 8

if ($OutFile -ne "") {
  $json | Out-File -FilePath $OutFile -Encoding utf8
  Write-Host "ShieldAI report written to $OutFile ($($checks.Count) checks, $($events.Count) events)."
} else {
  Write-Output $json
}

exit 0
