#!/usr/bin/env bash
# MANUALLY-SYNCED COPY of agent/macOS/collect.sh — do not edit this file
# independently. Re-sync (copy the main source over this file verbatim) and
# rebuild the .pkg (pkgbuild/productbuild, macOS-only tooling) whenever the
# main collector changes. This file previously drifted out of sync and
# shipped missing Bitdefender detection entirely — see
# agent/ARCHITECTURE.md's "Installer-source sync" note.
#
# ShieldAI macOS Posture Collector
# --------------------------------
# READ-ONLY. Collects security posture from native macOS tooling. Makes NO
# changes to the system. It does not scan for malware itself — it reports the
# state of macOS's built-in protections (FileVault, firewall, Gatekeeper, SIP,
# XProtect) and software-update status.
#
# Output: ShieldAI agent report schema v1 to -o <file>, or stdout.
# Always exits 0; missing data degrades to status "unknown".
#
# Usage: collect.sh [-o report.json] [-V 1.0.0]
# Pure bash + built-in macOS utilities. Uses `plutil`/`python3` only if present.

set -u
AGENT_VERSION="1.2.0"
OUTFILE=""

while getopts "o:V:" opt; do
  case "$opt" in
    o) OUTFILE="$OPTARG" ;;
    V) AGENT_VERSION="$OPTARG" ;;
    *) ;;
  esac
done

NOW_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\t'/ }"
  s="${s//$'\r'/ }"
  s="${s//$'\n'/ }"
  printf '"%s"' "$s"
}

CHECKS_JSON=""
EVENTS_JSON=""
SEC_TOOLS=""
add_tool() { local t; t="$(json_escape "$1")"; SEC_TOOLS="${SEC_TOOLS:+$SEC_TOOLS,}$t"; }
sanitize_int() { local v; v="$(printf '%s' "$1" | tr -cd '0-9' | head -c 9)"; printf '%s' "${v:-0}"; }

add_check() {
  local obj
  obj="{\"id\":$(json_escape "$1"),\"category\":$(json_escape "$2"),\"title\":$(json_escape "$3"),"
  obj+="\"status\":$(json_escape "$4"),\"severity\":$(json_escape "$5"),\"observed\":$(json_escape "$6"),"
  obj+="\"detail\":$(json_escape "$7"),\"cisControl\":$(json_escape "${8:-}")}"
  CHECKS_JSON="${CHECKS_JSON:+$CHECKS_JSON,}$obj"
}
add_event() {
  local obj
  obj="{\"ts\":$(json_escape "$NOW_UTC"),\"source\":$(json_escape "$1"),\"severity\":$(json_escape "$2"),"
  obj+="\"type\":$(json_escape "$3"),\"message\":$(json_escape "$4"),\"raw\":null}"
  EVENTS_JSON="${EVENTS_JSON:+$EVENTS_JSON,}$obj"
}
have() { command -v "$1" >/dev/null 2>&1; }

# ── host info ─────────────────────────────────────────────────
HOSTNAME_VAL="$(scutil --get ComputerName 2>/dev/null || hostname 2>/dev/null || echo unknown)"
PROD="$(sw_vers -productName 2>/dev/null || echo macOS)"
PVER="$(sw_vers -productVersion 2>/dev/null || echo '')"
OS_VERSION="$PROD $PVER"
ARCH="$(uname -m 2>/dev/null || echo unknown)"
LAST_BOOT="$(sysctl -n kern.boottime 2>/dev/null | sed -n 's/.*sec = \([0-9]*\).*/\1/p')"
if [ -n "$LAST_BOOT" ]; then
  LAST_BOOT="$(date -u -r "$LAST_BOOT" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo '')"
fi

# ── 1. FileVault disk encryption ──────────────────────────────
ENC_OBSERVED="unknown"; ENC_STATUS="unknown"; ENC_SEV="medium"
if have fdesetup; then
  if fdesetup status 2>/dev/null | grep -qi "FileVault is On"; then
    ENC_OBSERVED="FileVault On"; ENC_STATUS="pass"; ENC_SEV="info"
  else
    ENC_OBSERVED="FileVault Off"; ENC_STATUS="fail"; ENC_SEV="high"
  fi
fi
add_check "disk_encryption" "Protect" "Disk encryption (FileVault)" "$ENC_STATUS" "$ENC_SEV" "$ENC_OBSERVED" \
  "FileVault should be enabled to protect data at rest." "3"

# ── 2. Application firewall ───────────────────────────────────
FW_BIN="/usr/libexec/ApplicationFirewall/socketfilterfw"
FW_OBSERVED="unknown"; FW_STATUS="unknown"; FW_SEV="medium"
if [ -x "$FW_BIN" ]; then
  if "$FW_BIN" --getglobalstate 2>/dev/null | grep -qi "enabled"; then
    FW_OBSERVED="Application firewall enabled"; FW_STATUS="pass"; FW_SEV="info"
  else
    FW_OBSERVED="Application firewall disabled"; FW_STATUS="fail"; FW_SEV="high"
  fi
fi
add_check "firewall" "Protect" "Host firewall" "$FW_STATUS" "$FW_SEV" "$FW_OBSERVED" \
  "The macOS application firewall should be enabled." "4"

# ── 3. Gatekeeper ─────────────────────────────────────────────
if have spctl; then
  if spctl --status 2>/dev/null | grep -qi "assessments enabled"; then
    add_check "gatekeeper" "Protect" "Gatekeeper" "pass" "info" "enabled" \
      "Gatekeeper enforces signed/notarized apps." "10"
  else
    add_check "gatekeeper" "Protect" "Gatekeeper" "fail" "high" "disabled" \
      "Gatekeeper is disabled; unsigned apps can run freely." "10"
  fi
else
  add_check "gatekeeper" "Protect" "Gatekeeper" "unknown" "low" "Not determinable" \
    "Could not query Gatekeeper." "10"
fi

# ── 4. System Integrity Protection (SIP) ──────────────────────
if have csrutil; then
  if csrutil status 2>/dev/null | grep -qi "enabled"; then
    add_check "sip" "Protect" "System Integrity Protection" "pass" "info" "enabled" \
      "SIP protects critical system files from tampering." "4"
  else
    add_check "sip" "Protect" "System Integrity Protection" "fail" "high" "disabled" \
      "SIP is disabled; system files are unprotected." "4"
  fi
else
  add_check "sip" "Protect" "System Integrity Protection" "unknown" "low" "Not determinable" \
    "Could not query SIP." "4"
fi

# ── 5. XProtect / built-in malware tooling presence ───────────
XPROTECT="/Library/Apple/System/Library/CoreServices/XProtect.bundle"
[ -d "$XPROTECT" ] || XPROTECT="/System/Library/CoreServices/XProtect.bundle"
if [ -d "$XPROTECT" ]; then
  add_tool "Apple XProtect"
  add_check "av_present" "Protect" "Built-in malware protection" "pass" "info" "XProtect present" \
    "Apple's built-in XProtect malware signatures are present." "10"
else
  add_check "av_present" "Protect" "Built-in malware protection" "unknown" "low" "XProtect not found" \
    "Could not confirm XProtect presence." "10"
fi
# Third-party EDR/AV detection
if [ -d "/Applications/Falcon.app" ] || pgrep -q falcon 2>/dev/null; then add_tool "CrowdStrike Falcon"; fi
if [ -d "/Applications/SentinelOne" ] || pgrep -q SentinelAgent 2>/dev/null; then add_tool "SentinelOne"; fi
if [ -d "/Applications/Sophos Endpoint.app" ] || pgrep -qi "Sophos" 2>/dev/null; then add_tool "Sophos"; fi
if [ -d "/Applications/Malwarebytes.app" ]; then add_tool "Malwarebytes"; fi
if [ -d "/Applications/ESET Endpoint Security.app" ] || pgrep -qi "esets_daemon" 2>/dev/null; then add_tool "ESET"; fi
# Bitdefender: consumer (Bitdefender Antivirus for Mac) installs as one of a
# few app-bundle names depending on version/edition; GravityZone Business
# Security for Mac runs as a background agent under /Library/Bitdefender
# without necessarily showing an /Applications bundle at all, so the process
# check matters as much as the app-bundle one, not just as a fallback.
if [ -d "/Applications/Bitdefender Antivirus for Mac.app" ] || [ -d "/Applications/Bitdefender.app" ] \
  || [ -d "/Library/Bitdefender" ] || pgrep -qi "bitdefender" 2>/dev/null \
  || pgrep -qi "epsecurityd" 2>/dev/null || pgrep -qi "bdservicehost" 2>/dev/null; then
  add_tool "Bitdefender"
fi

# ── 5b. VPN client installed + tunnel active ──────────────────
VPN_CLIENTS=""
add_vpn() { VPN_CLIENTS="${VPN_CLIENTS:+$VPN_CLIENTS, }$1"; }
if [ -d "/Applications/Tunnelblick.app" ] || [ -d "/Applications/OpenVPN Connect.app" ] || pgrep -q openvpn 2>/dev/null; then add_vpn "OpenVPN"; fi
if [ -d "/Applications/Cisco/Cisco AnyConnect Secure Mobility Client.app" ] || pgrep -q vpnagentd 2>/dev/null; then add_vpn "Cisco AnyConnect"; fi
if [ -d "/Applications/WireGuard.app" ] || have wg; then add_vpn "WireGuard"; fi
if [ -d "/Applications/NordVPN.app" ]; then add_vpn "NordVPN"; fi
if [ -d "/Applications/Tailscale.app" ] || have tailscale; then add_vpn "Tailscale"; fi

if [ -n "$VPN_CLIENTS" ]; then
  add_check "vpn_client_installed" "Protect" "VPN client installed" "pass" "info" "$VPN_CLIENTS" \
    "A VPN client is installed on this host." "12"
else
  add_check "vpn_client_installed" "Protect" "VPN client installed" "warn" "low" "None detected" \
    "No known VPN client software was found on this host." "12"
fi

# Tunnel-active: scutil --nc catches macOS-native VPN framework configs
# (typically how AnyConnect/IPSec-type profiles register); WireGuard/
# Tailscale/modern OpenVPN use utun interfaces that don't register with
# scutil --nc, so an assigned-address utun check is the fallback signal.
TUNNEL_ACTIVE=0; TUNNEL_VENDOR=""
if have scutil && scutil --nc list 2>/dev/null | grep -q "(Connected)"; then
  TUNNEL_ACTIVE=1; TUNNEL_VENDOR="unknown"
elif ifconfig 2>/dev/null | grep -A2 '^utun' | grep -q 'inet '; then
  TUNNEL_ACTIVE=1; TUNNEL_VENDOR="unknown"
fi

if [ "$TUNNEL_ACTIVE" -eq 1 ]; then
  add_check "vpn_tunnel_active" "Protect" "VPN tunnel active" "pass" "info" "Connected ($TUNNEL_VENDOR)" \
    "An active VPN tunnel was detected." "12"
elif [ -n "$VPN_CLIENTS" ]; then
  add_check "vpn_tunnel_active" "Protect" "VPN tunnel active" "warn" "low" "Installed but not connected" \
    "A VPN client is installed but no active tunnel was detected right now." "12"
else
  add_check "vpn_tunnel_active" "Protect" "VPN tunnel active" "warn" "low" "No VPN client installed" \
    "No VPN client is installed, so no tunnel can be active." "12"
fi

# ── 5c. Password manager detection ────────────────────────────
PWD_MGRS=""
add_pwdmgr() { PWD_MGRS="${PWD_MGRS:+$PWD_MGRS, }$1"; }
if [ -d "/Applications/1Password.app" ] || [ -d "/Applications/1Password 7.app" ]; then add_pwdmgr "1Password"; fi
if [ -d "/Applications/Bitwarden.app" ]; then add_pwdmgr "Bitwarden"; fi
if [ -d "/Applications/Dashlane.app" ]; then add_pwdmgr "Dashlane"; fi
if [ -d "/Applications/KeePassXC.app" ]; then add_pwdmgr "KeePassXC"; fi
# LastPass has no reliable standalone macOS app bundle (primarily a browser
# extension there) — not checked, so this limitation is visible rather than
# silently under-detecting it as a false negative.

if [ -n "$PWD_MGRS" ]; then
  add_check "password_manager_installed" "Protect" "Password manager installed" "pass" "info" "$PWD_MGRS" \
    "A third-party password manager is installed on this host." "6"
else
  add_check "password_manager_installed" "Protect" "Password manager installed" "warn" "low" "None detected" \
    "No known third-party password manager was found on this host." "6"
fi

# ── 5d/5e. Browser-native password manager, Safe Browsing, version ──
# Chrome/Edge store their settings in the SAME cross-platform JSON
# Preferences file used on Windows/Linux, just at a macOS path — this is
# NOT a `defaults`/plist domain read (Chromium doesn't put these settings
# there); `defaults read` remains the right idiom only for genuinely
# native-macOS-preference apps, not Chrome/Edge. Uses python3 for a real
# JSON read when present (per this file's header comment), else a
# plain-text grep fallback, matching this file's existing
# PlistBuddy-or-fallback convention.
read_chromium_pref() {
  # $1 = Preferences file path, $2 = dotted key (e.g. "safebrowsing.enabled")
  local f="$1" key="$2"
  if have python3; then
    python3 -c "
import json,sys
try:
    with open(sys.argv[1]) as fh: d = json.load(fh)
    v = d
    for part in sys.argv[2].split('.'):
        v = v.get(part, {}) if isinstance(v, dict) else {}
    print(v if isinstance(v, bool) else '')
except Exception:
    print('')
" "$f" "$key" 2>/dev/null | tr '[:upper:]' '[:lower:]'
  else
    local leaf="${key##*.}"
    grep -o "\"${leaf}\":[a-z]*" "$f" 2>/dev/null | head -1 | cut -d: -f2
  fi
}

# Major-version floor per browser, "current stable major minus ~2" as of
# when this was written. Must be refreshed periodically and kept
# numerically identical across the Windows/Linux/macOS collectors — see
# agent/ARCHITECTURE.md's installer-sync / version-baseline note.
MIN_CHROME_MAJOR=128
MIN_EDGE_MAJOR=128
MIN_FIREFOX_MAJOR=128

BROWSERS_JSON=""
PWDMGR_CHROME="not-installed"; PWDMGR_EDGE="not-installed"; PWDMGR_FIREFOX="not-installed"

emit_browser_checks() {
  # $1 name, $2 key, $3 version, $4 min major, $5 pwdmgr_off(0/1),
  # $6 sb_off(0/1), $7 any_profile(0/1)
  local name="$1" key="$2" ver="$3" min_major="$4" pwdmgr_off="$5" sb_off="$6" any_profile="$7"
  local major current="true" pwdmgr="unknown" safebrowsing="unknown"
  major="$(echo "$ver" | cut -d. -f1)"
  if [ -n "$major" ] && [ "$major" -lt "$min_major" ] 2>/dev/null; then current="false"; fi
  if [ "$any_profile" -eq 1 ]; then
    pwdmgr="enabled"; [ "$pwdmgr_off" -eq 1 ] && pwdmgr="disabled"
    safebrowsing="enabled"; [ "$sb_off" -eq 1 ] && safebrowsing="disabled"
  fi
  if [ "$pwdmgr" != "unknown" ]; then
    add_check "browser_pwdmgr_$key" "Protect" "$name password manager" \
      "$([ "$pwdmgr" = "enabled" ] && echo pass || echo warn)" \
      "$([ "$pwdmgr" = "enabled" ] && echo info || echo low)" \
      "$pwdmgr" "Built-in $name password manager state." "6"
  fi
  if [ "$safebrowsing" != "unknown" ]; then
    add_check "browser_safebrowsing_$key" "Protect" "$name Safe Browsing" \
      "$([ "$safebrowsing" = "enabled" ] && echo pass || echo fail)" \
      "$([ "$safebrowsing" = "enabled" ] && echo info || echo medium)" \
      "$safebrowsing" "Built-in phishing/malware protection state." "9"
  fi
  add_check "browser_version_$key" "Identify" "$name version currency" \
    "$([ "$current" = "true" ] && echo pass || echo warn)" \
    "$([ "$current" = "true" ] && echo info || echo medium)" \
    "$ver" "Installed browser version compared against the supported baseline." "7"
  BROWSERS_JSON="${BROWSERS_JSON:+$BROWSERS_JSON,}{\"name\":$(json_escape "$name"),\"version\":$(json_escape "$ver"),\"safeBrowsing\":$(json_escape "$safebrowsing"),\"currentVersion\":$current}"
}

scan_mac_chromium_profile() {
  # $1 = path to Preferences file. Prints "pwdmgr_off|sb_off|any_profile".
  local f="$1" pwdmgr_off=0 sb_off=0 any_profile=0
  if [ -f "$f" ]; then
    any_profile=1
    [ "$(read_chromium_pref "$f" credentials_enable_service)" = "false" ] && pwdmgr_off=1
    [ "$(read_chromium_pref "$f" safebrowsing.enabled)" = "false" ] && sb_off=1
  fi
  echo "${pwdmgr_off}|${sb_off}|${any_profile}"
}

if [ -d "/Applications/Google Chrome.app" ]; then
  CHROME_VER="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "/Applications/Google Chrome.app/Contents/Info.plist" 2>/dev/null)"
  if [ -n "$CHROME_VER" ]; then
    IFS='|' read -r c_pwdmgr_off c_sb_off c_any_profile <<< "$(scan_mac_chromium_profile "$HOME/Library/Application Support/Google/Chrome/Default/Preferences")"
    emit_browser_checks "Google Chrome" "chrome" "$CHROME_VER" "$MIN_CHROME_MAJOR" "$c_pwdmgr_off" "$c_sb_off" "$c_any_profile"
    [ "$c_any_profile" -eq 1 ] && { PWDMGR_CHROME="enabled"; [ "$c_pwdmgr_off" -eq 1 ] && PWDMGR_CHROME="disabled"; }
  fi
fi

if [ -d "/Applications/Microsoft Edge.app" ]; then
  EDGE_VER="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "/Applications/Microsoft Edge.app/Contents/Info.plist" 2>/dev/null)"
  if [ -n "$EDGE_VER" ]; then
    IFS='|' read -r e_pwdmgr_off e_sb_off e_any_profile <<< "$(scan_mac_chromium_profile "$HOME/Library/Application Support/Microsoft Edge/Default/Preferences")"
    emit_browser_checks "Microsoft Edge" "edge" "$EDGE_VER" "$MIN_EDGE_MAJOR" "$e_pwdmgr_off" "$e_sb_off" "$e_any_profile"
    [ "$e_any_profile" -eq 1 ] && { PWDMGR_EDGE="enabled"; [ "$e_pwdmgr_off" -eq 1 ] && PWDMGR_EDGE="disabled"; }
  fi
fi

# Firefox uses a different preferences format entirely (prefs.js, a
# JS-literal text file, not JSON) — handled separately, same idiom as the
# Windows/Linux collectors' Firefox checks, not an oversight.
if [ -d "/Applications/Firefox.app" ]; then
  FIREFOX_VER="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "/Applications/Firefox.app/Contents/Info.plist" 2>/dev/null)"
  if [ -n "$FIREFOX_VER" ]; then
    ff_pwdmgr_off=0; ff_sb_off=0; ff_any_profile=0
    for pf in "$HOME/Library/Application Support/Firefox/Profiles/"*.default*/prefs.js; do
      [ -f "$pf" ] || continue
      ff_any_profile=1
      grep -Eq 'user_pref\("signon\.rememberSignons",[[:space:]]*false\)' "$pf" && ff_pwdmgr_off=1
      grep -Eq 'user_pref\("browser\.safebrowsing\.(malware|phishing)\.enabled",[[:space:]]*false\)' "$pf" && ff_sb_off=1
    done
    emit_browser_checks "Mozilla Firefox" "firefox" "$FIREFOX_VER" "$MIN_FIREFOX_MAJOR" "$ff_pwdmgr_off" "$ff_sb_off" "$ff_any_profile"
    [ "$ff_any_profile" -eq 1 ] && { PWDMGR_FIREFOX="enabled"; [ "$ff_pwdmgr_off" -eq 1 ] && PWDMGR_FIREFOX="disabled"; }
  fi
fi

PWDMGRS_BROWSER_JSON="{\"chrome\":$(json_escape "$PWDMGR_CHROME"),\"edge\":$(json_escape "$PWDMGR_EDGE"),\"firefox\":$(json_escape "$PWDMGR_FIREFOX")}"

# ── 6. Pending software updates ───────────────────────────────
if have softwareupdate; then
  SU_OUT="$(softwareupdate -l 2>&1)"
  if printf '%s' "$SU_OUT" | grep -qi "No new software available"; then
    add_check "patches" "Identify" "Pending OS updates" "pass" "info" "0 pending" \
      "No pending macOS updates." "7"
  else
    NUP="$(sanitize_int "$(printf '%s' "$SU_OUT" | grep -c '^\s*\* ')")"
    if [ "$NUP" -eq 0 ]; then
      add_check "patches" "Identify" "Pending OS updates" "unknown" "low" "Not determinable" \
        "Could not parse softwareupdate output." "7"
    elif [ "$NUP" -le 5 ]; then
      add_check "patches" "Identify" "Pending OS updates" "warn" "medium" "$NUP pending" \
        "Some macOS updates are pending." "7"
    else
      add_check "patches" "Identify" "Pending OS updates" "fail" "high" "$NUP pending" \
        "Many macOS updates are pending; patch promptly." "7"
    fi
  fi
else
  add_check "patches" "Identify" "Pending OS updates" "unknown" "low" "Not determinable" \
    "softwareupdate not available." "7"
fi

# ── 7. Admin accounts ─────────────────────────────────────────
if have dseditgroup || have dscl; then
  ADMINS="$(dscl . -read /Groups/admin GroupMembership 2>/dev/null | sed 's/GroupMembership: //')"
  if [ -n "$ADMINS" ]; then
    NADM="$(sanitize_int "$(echo "$ADMINS" | tr ' ' '\n' | grep -c .)")"
    ST="pass"; SV="info"
    [ "$NADM" -gt 3 ] && ST="warn" && SV="medium"
    [ "$NADM" -gt 6 ] && ST="fail" && SV="high"
    add_check "admins" "Identify" "Administrator accounts" "$ST" "$SV" "$NADM account(s)" \
      "Limit admin accounts to the minimum necessary." "5"
  else
    add_check "admins" "Identify" "Administrator accounts" "unknown" "low" "Not determinable" \
      "Could not read admin group membership." "5"
  fi
fi

# ── 8. Automatic updates configured ───────────────────────────
AUTO_PLIST="/Library/Preferences/com.apple.SoftwareUpdate"
AUTO_ON="$(defaults read "$AUTO_PLIST" AutomaticCheckEnabled 2>/dev/null || echo '')"
if [ "$AUTO_ON" = "1" ]; then
  add_check "auto_updates" "Protect" "Automatic update checks" "pass" "info" "enabled" \
    "Automatic update checking is enabled." "7"
else
  add_check "auto_updates" "Protect" "Automatic update checks" "warn" "low" "not enabled / unknown" \
    "Consider enabling automatic update checks." "7"
fi

# ── installed software inventory (read-only) ──────────────────
# Enumerates installed applications + versions. Prefers system_profiler's JSON
# output (parsed with the built-in plutil/python where available); falls back to
# reading each /Applications/*.app Info.plist. Read-only. Feeds CVE matching.
SOFTWARE_JSON=""
build_software() {
  local first=1 name ver
  # Fallback approach that needs no extra tools: read app bundle Info.plists.
  local appdir line
  for appdir in /Applications/*.app /Applications/*/*.app; do
    [ -d "$appdir" ] || continue
    name="$(basename "$appdir" .app)"
    ver=""
    if [ -f "$appdir/Contents/Info.plist" ]; then
      ver="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$appdir/Contents/Info.plist" 2>/dev/null)"
    fi
    [ -z "$name" ] && continue
    if [ $first -eq 1 ]; then first=0; else SOFTWARE_JSON+=","; fi
    SOFTWARE_JSON+="{\"name\":$(json_escape "$name"),\"version\":$(json_escape "${ver:-}")}"
  done
}
build_software 2>/dev/null || SOFTWARE_JSON=""

# ── inventory ─────────────────────────────────────────────────
VPN_CLIENTS_JSON=""
if [ -n "$VPN_CLIENTS" ]; then
  IFS=',' read -ra _vc <<< "$VPN_CLIENTS"
  for v in "${_vc[@]}"; do
    v="$(echo "$v" | sed 's/^ *//;s/ *$//')"
    VPN_CLIENTS_JSON="${VPN_CLIENTS_JSON:+$VPN_CLIENTS_JSON,}$(json_escape "$v")"
  done
fi
VPN_INV="{\"installedClients\":[${VPN_CLIENTS_JSON}],\"tunnelActive\":$([ "$TUNNEL_ACTIVE" -eq 1 ] && echo true || echo false),\"activeTunnelClient\":$(json_escape "${TUNNEL_VENDOR:-}")}"

PWD_MGRS_JSON=""
if [ -n "$PWD_MGRS" ]; then
  IFS=',' read -ra _pm <<< "$PWD_MGRS"
  for p in "${_pm[@]}"; do
    p="$(echo "$p" | sed 's/^ *//;s/ *$//')"
    PWD_MGRS_JSON="${PWD_MGRS_JSON:+$PWD_MGRS_JSON,}$(json_escape "$p")"
  done
fi
PWDMGR_INV="{\"thirdPartyInstalled\":[${PWD_MGRS_JSON}],\"browserNative\":${PWDMGRS_BROWSER_JSON}}"

INV="{\"localAdmins\":[],\"installedSecurityTools\":[${SEC_TOOLS}],"
INV+="\"diskEncryption\":$(json_escape "$ENC_OBSERVED"),\"pendingPatches\":0,"
INV+="\"firewall\":$(json_escape "$FW_OBSERVED"),"
INV+="\"vpn\":${VPN_INV},\"passwordManagers\":${PWDMGR_INV},\"browsers\":[${BROWSERS_JSON}],"
INV+="\"software\":[${SOFTWARE_JSON}]}"

# ── assemble report ───────────────────────────────────────────
REPORT="{\"agentVersion\":$(json_escape "$AGENT_VERSION"),\"schema\":1,"
REPORT+="\"host\":{\"hostname\":$(json_escape "$HOSTNAME_VAL"),\"os\":\"macos\","
REPORT+="\"osVersion\":$(json_escape "$OS_VERSION"),\"arch\":$(json_escape "$ARCH"),"
REPORT+="\"lastBootUtc\":$(json_escape "${LAST_BOOT:-}"),\"collectedAtUtc\":$(json_escape "$NOW_UTC")},"
REPORT+="\"checks\":[${CHECKS_JSON}],\"events\":[${EVENTS_JSON}],\"inventory\":${INV}}"

if [ -n "$OUTFILE" ]; then
  printf '%s' "$REPORT" > "$OUTFILE"
  echo "ShieldAI report written to $OUTFILE"
else
  printf '%s\n' "$REPORT"
fi

exit 0
